[Server]
Host = "0.0.0.0:30523"

[Log]
# Level's value can INFO、DEBUG、ERROR、WARNING, the default value is INFO
Level = "DEBUG"

[Register]
Enable = false
GameID = 123456
SvcName = "svc-abc"
PodName = "pod-abc"
RemoteHost = "192.168.8.1"
RemotePort = 9981
LocalHost = "192.168.8.2"
LocalPort = 30054


[RoomManage]
Enable = true
SvcName = "svc-200773-0-0"
PodName = " deploy-200773-0-0-c7774c4cc-k6cbb"
RemoteHost = "directory10.matchvs.com"
RemotePort = 9982